### ISSUE TITLE
[SelectMulti] Add icon to input

### ISSUE THREAD

**Issue by zDudaHang** [laboratoriobridge/bold#761] opened 2022-07-20 14:36 UTC
## Component to amend
SelectMulti

## Visual
When the `multiple` prop is not selected the icon appears correctly, however if it is true the icon disappears.

Without `multiple`:
![Screenshot from 2022-07-20 11-29-51](https://user-images.githubusercontent.com/25747989/180008185-c7050cdf-5c90-4cb5-9527-39f8e6eee185.png)

With `multiple`:
![Screenshot from 2022-07-20 11-29-56](https://user-images.githubusercontent.com/25747989/180008201-47a4bd62-df1e-4f70-92a4-d942678db873.png)

**Comment by Andrevmatias** [comment] 2023-11-17 21:00
Duplicate of #519

**Closed by Andrevmatias** 2023-11-17 21:00 UTC
Labels: duplicate, enhancement
